# Default runtime configuration for My AI Agent
# These values are loaded by a Pydantic `Settings` class and can be
# overridden by environment variables or CLI parameters.

llm:
  provider: openai            # "openai", "azure", "cohere", etc.
  model_name: gpt-4o-mini     # Default chat model
  temperature: 0.0            # Deterministic answers
  max_tokens: 4096            # Hard ceiling for responses

embeddings:
  provider: openai
  model_name: text-embedding-3-small
  chunk_size: 1000            # Characters per chunk

vector_store:
  type: chroma                # "chroma", "faiss", "redis", etc.
  persist_directory: ./chroma_db

memory:
  window_size: 8              # How many turns to keep in short-term memory

agent:
  type: conversational-react-description
  verbose: true

# Enable/disable built-in tools
tools:
  enabled:
    - search
    - calculator